services:
  web:
    build: .
    container_name: chatapp_web
    command: /wait-for-it.sh postgres:5432 -- /app/setup.sh  # Run the script for migrations and superuser creation
    # command: /app/setup.sh
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: chatapp_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: chatapp_postgres
    environment:
      - POSTGRES_DB=chat_db
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=chat@admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: chatapp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles  # Ensure static files are accessible to Nginx
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
